export const starkQuotes = [
  "Sometimes you gotta run before you can walk.",
  "I am Iron Man.",
  "Genius, billionaire, playboy, philanthropist.",
  "I told you. I don't want to join your super secret boy band.",
  "If we can't protect the Earth, you can be damn well sure we'll avenge it.",
  "We create our own demons.",
  "You can take away my house, all my tricks and toys, but one thing you can't take away—I am Iron Man.",
  "Does Mother know you weareth her drapes?",
  "Following's not really my style.",
  "I loved you in A Christmas Story, by the way.",
  "I already told you, I don't want to join your super-secret boy band.",
  "Doth mother know you weareth her drapes?",
  "That man is playing Galaga! Thought we wouldn't notice. But we did.",
  "I thought we were having a moment.",
  "Let's face it, this is not the worst thing you've caught me doing.",
  "I have a plan: Attack.",
  "You know, it's moments like these when I realize what a superhero I am.",
  "It's not about how much we lost. It's about how much we have left.",
  "Part of the journey is the end.",
  "I love you 3000.",
  "No amount of money ever bought a second of time.",
  "Everybody wants a happy ending, right? But it doesn't always roll that way.",
  "I'm sorry, Earth is closed today. You better pack it up and get outta here.",
  "You're missing the point. There's no throne, there is no version of this where you come out on top.",
  "Drop your socks and grab your Crocs, we're about to get wet on this ride.",
  "I'm just not the hero type. Clearly.",
  "You walk away from this, and I'll chop your legs off.",
  "Don't do anything I would do, and definitely don't do anything I wouldn't do.",
  "It's an imperfect world, but it's the only one we got.",
  "What is the point of owning a race car if you can't drive it?",
  "You can't afford me.",
  "I'm a huge fan of the way you lose control and turn into an enormous green rage monster.",
  "I just want peace. Turns out resentment is corrosive, and I hate it.",
  "I build neat stuff, got a great girl, occasionally save the world. So why can't I sleep?",
  "My armor was never a distraction or a hobby, it was a cocoon.",
  "You're right. I am not the guy to make the sacrifice play.",
  "I don't like it when people hand me things.",
  "The truth is... I am Iron Man.",
  "We have a Hulk.",
  "Keep your friends rich and your enemies rich, and wait to find out which is which.",
  "Is it better to be feared or respected? I say, is it too much to ask for both?",
];
